config/routes.rb
Mentorland::Application.routes.draw do
  authenticated :user do  
    root :to => "home#index"
  end
  root :to => "home#index"
  get "home" => "home#index"
  get "index" => "home#index"
  devise_for :users

  get "profile" => "users#profile"	
  post "addMentor" => "users#addMentor"
  post "addStudent" => "users#addStudent"

  get "mentor" => "mentors#show"
  post "mentor" => "mentors#createCourse"
  
  get "student" => "students#show"
  post "student" => "students#search"
  post "student/EmptyCart" => "students#EmptyCart"
  post "student/addtoCart" => "students#addtoCart"
  post "student/checkout" => "students#checkout"
  get "credit_cards" => "creditcards#show"
	post "credit_cards" => "creditcards#create"
  get "admin" => "users#index"

end

app/models/student.rb
class Student < User
  has_many :courses, through: :enrollments
  has_many :courses, through: :line_items
	has_many :credit_cards, through: :hascreditcards
end

app/controllers/students_controller.rb
require 'rubygems'
require 'active_merchant'
class StudentsController < ApplicationController
  @@static_search_result ||= nil
  # GET /students/1
  def show
    @student = current_user
    my_enrollments = Enrollment.where(:user_id => @student.id)
    my_courses = []
    my_enrollments.each do |e|
      my_courses << Course.find(e.course_id)
    end

    # call search methods
    if params[:search].blank?
      #flash[:notice] = "Please Type in Keywords"
    else
      if params[:search_type] == 'Search by Course'
        #flash[:notice] = "Search by Course"
        search_by_course
      else
        #flash[:notice] = "Search by Mentor"
        search_by_mentor
      end
    end

    @my_courses = my_courses.paginate(:page => params[:mycourse_page], :per_page => 6)
    my_line_items = LineItem.where(:user_id => @student.id)
    my_cart = []
    @total_price = 0
    my_line_items.each do |e|
      course = Course.find(e.course_id)
      my_cart << course
      @total_price += course.price
    end
    @my_cart = my_cart.paginate(:page => params[:mycart_page], :per_page => 4)
    @allcourses = Course.paginate(:page => params[:courses_page], :per_page => 6)
    @course_map = []
    @my_courses.each do |course|
      @course_map << course
    end
    @my_cart.each do |course|
      @course_map << course
    end
    @course_list = @@static_search_result
  end

  # POST /students/1	add a course to a student
  def addCourse(course_id)
    enrollment = Enrollment.create(:course_id => course_id, :user_id => current_user.id)
		enrollment.save
  end

  def search
    # call search methods
    if params[:search].blank?
      #flash[:notice] = "Please Type in Keywords"
    else
      if params[:search_type] == 'Search by Course'
        #flash[:notice] = "Search by Course"
        search_by_course
      else
        #flash[:notice] = "Search by Mentor"
        search_by_mentor
      end
    end
  end

  def search_by_course
    if params[:search].blank?
      @typein = nil
    else
      @typein = params[:search]
      @search = Sunspot.search(Course) do
        keywords params[:search], :highlight => true
        paginate :page => params[:search_page], :per_page => 6
        order_by :price, :asc
      end
      @course_list = @search.results
      @@static_search_result = @course_list
    end
  end

  def search_by_mentor
    @search_mentors = Sunspot.search(Mentor) do
      keywords params[:search]
    end
    @typein = params[:search]
    if @search_mentors.results.blank?
      @course_list = nil
    else
      #@typein = params[:search]
      @search_mentors.results.each do |user|
        userid = user.id
        @search = Sunspot.search(Course) do
          with :user_id, userid
          paginate :page => params[:search_page], :per_page => 6
          order_by :price, :asc
        end
        @course_list = @search.results
        @@static_search_result = @course_list
      end
    end
  end
	
  # POST /students/1	add a course to a student
  def addtoCart
    @line_item = LineItem.create(:course_id => params[:course_id], :user_id => current_user.id)

    respond_to do |format|
      if @line_item.save
        flash[:notice] = "This course was successfully added to cart!"
        format.html { redirect_to student_url }
      else
				flash[:error] = "Cannot add this course to cart!"
				#@line_item.errors.each{|attr,msg| puts "#{attr} - #{msg}" }
        format.html { redirect_to student_url }
      end
    end
  end
	
	def EmptyCart
		@my_cart = []
		LineItem.delete_all(:user_id => current_user.id)
		flash[:notice] = "Your cart is empty!" 
		respond_to do |format|
			format.html { redirect_to student_url }
		end
	end
	
	def checkout		
		my_line_items = LineItem.where(:user_id => current_user.id)
		my_cart = []
		@total_price = 0
    my_line_items.each do |e|
			course = Course.find(e.course_id)
      my_cart << course
			@total_price += course.price			
    end		
		@my_cart = my_cart
		@card = CreditCard.find(params[:credit_card_id])
		# Use the TrustCommerce test servers
		ActiveMerchant::Billing::Base.mode = :test

		gateway = ActiveMerchant::Billing::TrustCommerceGateway.new(
								:login => 'TestMerchant',
								:password => 'password')

		# ActiveMerchant accepts all amounts as Integer values in cents
		amount = @total_price * 100

		# The card verification value is also known as CVV2, CVC2, or CID
		credit_card = ActiveMerchant::Billing::CreditCard.new(
										:first_name         => @card.first_name,
										:last_name          => @card.last_name,
										:number             => @card.number,
										:month              => @card.month.to_i,
										:year               => @card.year.to_i,
										:verification_value => @card.verification_value)

		# Validating the card automatically detects the card type
		if credit_card.valid?
			# Capture $10 from the credit card
			response = gateway.purchase(amount.to_i, credit_card)	

			if response.success?	
				my_line_items.each do |e|
					addCourse(e.course_id)
				end					
				my_line_items = []
				LineItem.delete_all(:user_id => current_user.id)
				flash[:notice] = "Successfully charged $#{sprintf("%.2f", amount / 100)} to the credit card #{credit_card.display_number}"
				respond_to do |format|
					format.html { redirect_to student_url }
				end
			else
				flash[:error] = "Checkout failed"
				respond_to do |format|
					format.html { redirect_to student_url }
				end
			end
		else
				flash[:error] = "Credit Card invalid"
				respond_to do |format|
					format.html { redirect_to student_url }
				end
		end
	end
end

app/views/students/_cart.erb
<h3>My Cart</h3>
<table class="table table-condensed">
	<tr>
	  <td style="height: 30px"><b>Course Name</b></td>
      <td style="height: 30px"><b>Price</b></td>
      <td style="height: 30px"><b>Capacity</b></td>
	</tr>
	<% @my_cart.each do |course| %>
	<tr>    
	  <td style="height: 60px"><%= course.name %></td>
      <td style="height: 60px"><%= course.price %></td>
      <td style="height: 60px"><%= course.capacity %></td>
	</tr>
	<% end %>
</table>
<table class="table table-cart">
  <tr>
    <td style="height: 60px"><h4> Total price is <%= @total_price %></h4></td>
    <td style="height: 60px"><%= button_to("Empty Cart", {:controller => "students", :action => "EmptyCart"}, :remote => false, confirm: 'Are you sure to empty the cart?', class: "btn btn-danger") %></td>
    <td style="height: 60px"><%= button_to("Checkout", credit_cards_url, method: :get, :remote => false, class: "btn btn-success") %></td>
  </tr>
</table>

app/views/students/_courses.erb
<table class="table table-condensed">
  <tr>
    <td style="height: 30px"><b>Course</b></td>
    <td style="height: 30px"><b>Price</b></td>
    <td style="height: 30px"><b>Capacity</b></td>
    <td style="height: 30px"></td>
  </tr>
  <% @allcourses.each do |course| %>
      <tr>
        <td style="height: 60px"><%= course.name %></td>
        <td style="height: 60px"><%= course.price %></td>
        <td style="height: 60px"><%= course.capacity %></td>
        <td style="height: 60px"><%= button_to("Add to Cart", {:controller => "students", :action => "addtoCart", :course_id => course.id}, :remote => false, class: "btn btn-warning") %></td>
      </tr>
  <% end %>
</table>

app/views/students/_mycourse.erb
<h3>My Courses</h3>
<table class="table table-condensed">
<tr>
        <td style="height: 30px"><b>Course Name</b></td>
        <td style="height: 30px"><b>Price</b></td>
        <td style="height: 30px"><b>Capacity</b></td>
</tr>
<% @my_courses.each do |course| %>
  <tr>
        <td style="height: 60px"><%= course.name %></td>
        <td style="height: 60px"><%= course.price %></td>
        <td style="height: 60px"><%= course.capacity %></td>
  </tr>
<% end %>
</table>

app/views/students/_search.erb
<h3>Search Results</h3>
<table class="table table-condensed">
  <tr>
    <td style="height: 30px"><b>Course</b></td>
    <td style="height: 30px"><b>Price</b></td>
    <td style="height: 30px"><b>Capacity</b></td>
    <td style="height: 30px"></td>
  </tr>
  <% @course_list.each do |course| %>
      <tr>
        <td style="height: 60px"><%= course.name %></td>
        <td style="height: 60px"><%= course.price %></td>
        <td style="height: 60px"><%= course.capacity %></td>
        <td style="height: 60px"><%= button_to("Add to Cart", {:controller => "students", :action => "addtoCart", :course_id => course.id}, :remote => false, class: "btn btn-info") %></td>
      </tr>
  <% end %>
</table>

app/views/students/show.erb
<div class="search-type row">
  <div class="span12">
	<%= form_tag student_path, :method => :get do %>
        <table class="search-table">
          <tr>
            <td style="height: 50px"><%= text_field_tag :search, params[:search], class: "search-query span7", placeholder: "Search courses or mentors here..."%></td>
            <td style="width: 120px"></td>
            <td style="height: 50px"><button type="submit" class="btn btn-large btn-primary" id="search_button">Search</button></td>
          </tr>
          <tr>
            <td><%= select_tag :search_type, options_for_select(['Search by Course', 'Search by Mentor'], params[:search_type]), {:search_type => 'Search by Course'} %></td>
          </tr>
        </table>
	<% end %>
  </div>
</div>
<div class="ipad tabbable tabs-left">
  <ul class="nav nav-tabs" id="myTab">
    <li class="active">
		<a href="#mycourse" data-toggle="tab"><h4>My courses</h4></a>
	</li>
    <li>
		<a href="#allcourse" data-toggle="tab"><h4>All courses</h4></a>
	</li>
    <li>
		<a href="#searchresult" data-toggle="tab" id="search_tab"><h4>Search results</h4></a>
	</li>
    <li>
		<a href="#mycart" data-toggle="tab"><h4>My cart</h4></a>
	</li>
  </ul>  
  <div class="tab-content" id="tabs">
    <div class="tab-pane active" id="mycourse">	
		<%= render "mycourse" %>
		<%= will_paginate @my_courses, :param_name => 'mycourse_page' %>
	</div>
    <div class="tab-pane" id="allcourse">
      <h3>All Courses</h3>
		<%= render "courses" %>
		<%= will_paginate @allcourses, :param_name => 'courses_page' %>
	</div>
    <div class="tab-pane" id="searchresult">
      <% if @course_list.blank? %>
          <h3>No Match Results! List all courses.</h3>
          <%= render "courses" %>
          <%= will_paginate @allcourses, :param_name => 'courses_page' %>
      <% else %>
          <%= render "search" %>
          <%= will_paginate @course_list, :param_name => 'search_page', class: "pagination" %>
      <% end %>
	</div>
    <div class="tab-pane" id="mycart">	
		<%= render "cart" %>
		<%= will_paginate @my_cart, :param_name => 'mycart_page' %>	
	</div>
  </div>
</div>

<%= stylesheet_link_tag 'gmaps4rails' %>
<%= gmaps4rails(@course_map.to_gmaps4rails )%>


<!-- javascript -->
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="javascripts/bootstrap.js"></script>
	<script src="javascripts/student.js"></script>