config/routes.rb
Mentorland::Application.routes.draw do
  authenticated :user do  
    root :to => "home#index"
  end
  root :to => "home#index"
  get "home" => "home#index"
  get "index" => "home#index"
  devise_for :users

  get "profile" => "users#profile"	
  post "addMentor" => "users#addMentor"
  post "addStudent" => "users#addStudent"

  get "mentor" => "mentors#show"
  post "mentor" => "mentors#createCourse"
  
  get "student" => "students#show"
  post "student" => "students#search"
  post "student/EmptyCart" => "students#EmptyCart"
  post "student/addtoCart" => "students#addtoCart"
  post "student/checkout" => "students#checkout"
  get "credit_cards" => "creditcards#show"
	post "credit_cards" => "creditcards#create"
  get "admin" => "users#index"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Capacity</th>
    <th>Time</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.name %></td>
    <td><%= course.description %></td>
    <td><%= course.price %></td>
    <td><%= course.capacity %></td>
    <td><%= course.time %></td>
    <td><%= course.location %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Description:</b>
  <%= @course.description %>
</p>

<p>
  <b>Price:</b>
  <%= @course.price %>
</p>

<p>
  <b>Capacity:</b>
  <%= @course.capacity %>
</p>

<p>
  <b>Time:</b>
  <%= @course.time %>
</p>

<p>
  <b>Location:</b>
  <%= @course.location %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>