config/routes.rb
Mentorland::Application.routes.draw do
  authenticated :user do  
    root :to => "home#index"
  end
  root :to => "home#index"
  get "home" => "home#index"
  get "index" => "home#index"
  devise_for :users

  get "profile" => "users#profile"	
  post "addMentor" => "users#addMentor"
  post "addStudent" => "users#addStudent"

  get "mentor" => "mentors#show"
  post "mentor" => "mentors#createCourse"
  
  get "student" => "students#show"
  post "student" => "students#search"
  post "student/EmptyCart" => "students#EmptyCart"
  post "student/addtoCart" => "students#addtoCart"
  post "student/checkout" => "students#checkout"
  get "credit_cards" => "creditcards#show"
	post "credit_cards" => "creditcards#create"
  get "admin" => "users#index"

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'My Profile', profile_url %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Be Admin', admin_url %>
      </li>
    <% end %>
    <% if current_user.has_role? :mentor %>
      <li>
      <%= link_to 'Be Mentor', mentor_url %>
      </li>
    <% end %>
    <% if current_user.has_role? :student %>
      <li>
      <%= link_to 'Be Student', student_url %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "mentorland" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "mentorland" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Twitter Bootstrap 2.3 %>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
          <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
            </div>
          </div>
	  <%= yield %>
        </div>
      </div>
    </main>
    <%= yield :scripts %>
  </body>
</html>